export const ROUTES = {
    ROOT_PATH: "/",
    HOME_PATH: "/home",
    PAGE_PATH: "/page",
    PAGE_PARAM: "/:page",
    HOTEL_PATH: "/hotels",
    ID_PARAM: "/:id",
    SIGN_UP_PATH: "/signup",
    SIGN_IN_PATH: "/signin",
    DASHBOARD: "/dashboard",
    FORGOT_PASSWORD: "/forgotpassword",
    USERS_PATH: "/users",
    VERIFY_PATH: "/verify",
    AUTHTOKEN_PARAM: "/:authToken",
    RECOVER_PATH: "/recover",
    EMAIL_PARAM: "/:email",
    RECOVERY_LINK_PARAM: "/:recoveryLink",
    CHECK_CROPS: "/checkcrops",
    CROP_CHECK: "/cropcheck"
}
