export const REQUEST_CROPS_LIST = 'REQUEST_CROPS_LIST';
export const RECEIVE_CROPS_LIST = 'RECEIVE_CROPS_LIST';
export const REQUEST_CROPS_PH = 'REQUEST_CROPS_PH';
export const RECEIVE_CROPS_PH = 'RECEIVE_CROPS_PH';
export const REQUEST_WEATHER = 'REQUEST_WEATHER';
export const RECEIVE_WEATHER = 'RECEIVE_WEATHER';
export const REQUEST_CROPS_FOR_PLANTING = 'REQUEST_CROPS_FOR_PLANTING';
export const RECEIVE_CROPS_FOR_PLANTING = 'RECEIVE_CROPS_FOR_PLANTING';
export const REQUEST_CROP_PLANTABILITY  = 'REQUEST_CROP_PLANTABILITY';
export const RECEIVE_CROP_PLANTABILITY = 'RECEIVE_CROP_PLANTABILITY';
export const REQUEST_FERTILIZERS = 'REQUEST_FERTILIZERS';
export const RECEIVE_FERTILIZERS = 'RECEIVE_FERTILIZERS';
export const REQUEST_ADD_USER_CHECK_CROP_QUERY = "REQUEST_ADD_USER_CHECK_CROP_QUERY";
export const RECEIVE_ADD_USER_CHECK_CROP_QUERY = "RECEIVE_ADD_USER_CHECK_CROP_QUERY";
export const REQUEST_ADD_USER_CROPS_CHECK_QUERY = "REQUEST_ADD_USER_CROPS_CHECK_QUERY";
export const RECEIVE_ADD_USER_CROPS_CHECK_QUERY = "RECEIVE_ADD_USER_CROPS_CHECK_QUERY";

